on:
  release:
    types: [ created ]

jobs:
  go-binary-release:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [ linux, windows, darwin ]
        goarch: [ amd64, arm, arm64 ]
        exclude:
          - goarch: arm
            goos: darwin
          - goarch: arm64
            goos: windows
          - goarch: arm
            goos: windows
    steps:
      - uses: actions/checkout@v2
      - uses: wangyoucao577/go-release-action@v1.22
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          asset_name: s3dir-${{ github.ref_name }}-${{ matrix.goos }}-${{ matrix.goarch }}
          binary_name: "s3dir"
          extra_files: README.md
          sha256sum: true
          md5sum: false
          overwrite: true
  docker-image:
    name: Build Docker Image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ github.ref_name }}
          platforms: |
            linux/amd64
            linux/arm64
            linux/arm/v7
